name: reviewdog
on: [pull_request]

jobs:

  golangci-lint-github-pr-review:
    name: runner / golangci-lint (github-pr-review)
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
      - name: golangci-lint w/ github-pr-review
        uses: docker://reviewdog/action-golangci-lint:v1 # Pre-built image
        with:
          github_token: ${{ secrets.github_token }}
          golangci_lint_flags: "--config=.github/.golangci.yml ./testdata"
          tool_name: "golangci-lint-github-pr-review"
          reporter: "github-pr-review"

    # Use golint via golangci-lint binary with "warning" level.
    golint:
      name: runner / golint
      runs-on: ubuntu-latest
      steps:
        - name: Check out code into the Go module directory
          uses: actions/checkout@v1
        - name: golint
          uses: reviewdog/action-golangci-lint@v1
          with:
            github_token: ${{ secrets.github_token }}
            golangci_lint_flags: "--disable-all -E golint"
            tool_name: golint # Change reporter name.
            level: warning # GitHub Status Check won't become failure with this level.

  govet:
    name: runner / govet
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
      - name: govet
        uses: docker://reviewdog/action-golangci-lint:v1
        with:
          github_token: ${{ secrets.github_token }}
          golangci_lint_flags: "--disable-all -E govet ./testdata"
          tool_name: govet

  errcheck:
    name: runner / errcheck
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
      - name: errcheck
        uses: docker://reviewdog/action-golangci-lint:v1
        with:
          github_token: ${{ secrets.github_token }}
          golangci_lint_flags: "--disable-all -E errcheck ./testdata"
          tool_name: errcheck
          level: warning